### ISSUE TITLE
Passing "YYYY-MM" (e.g. "2027-08") for date with isDate validation crashes

### ISSUE THREAD

**Issue by yuval-a** [express-validator/express-validator#1300]
## Describe the bug

If you only pass a year and a month string for a date body parameter  with a `isDate` validation - everything crashes.
## To Reproduce

Define a isDate validation, e.g. with a validation schema that has:

```
expirationDate: {
    optional: true,
    isDate: { errorMessage: 'Date must be a valid date' }
  }
```
## Expected behavior

If the date is not a valid date format - send the error message in the response.

## Current behavior
For other kinds of malformed date strings - it works correctly, shows the message, but for this specific format - it crashes.

 
## Environment:

- Express-validator version: 7.1.0
- Express version: 4.19.2
- Node.js version: 20.11.0

## Stack trace:

```
TypeError: Cannot read properties of undefined (reading 'length')
    at StandardValidation.isDate [as validator] (/Users/yuvalaloni/dev/passportcard-shopping-cart/src/api/node_modules/validator/lib/isDate.js:90:19)
    at /Users/yuvalaloni/dev/passportcard-shopping-cart/src/api/node_modules/express-validator/lib/context-items/standard-validation.js:18:33
    at Array.forEach (<anonymous>)
    at StandardValidation.run (/Users/yuvalaloni/dev/passportcard-shopping-cart/src/api/node_modules/express-validator/lib/context-items/standard-validation.js:17:16)
    at /Users/yuvalaloni/dev/passportcard-shopping-cart/src/api/node_modules/express-validator/lib/chain/context-runner-impl.js:41:39
    at Array.map (<anonymous>)
    at ContextRunnerImpl.run (/Users/yuvalaloni/dev/passportcard-shopping-cart/src/api/node_modules/express-validator/lib/chain/context-runner-impl.js:34:70)
    at middleware (/Users/yuvalaloni/dev/passportcard-shopping-cart/src/api/node_modules/express-validator/lib/middlewares/check.js:15:26)
    at Layer.handle [as handle_request] (/Users/yuvalaloni/dev/passportcard-shopping-cart/src/api/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/yuvalaloni/dev/passportcard-shopping-cart/src/api/node_modules/express/lib/router/route.js:149:13)
```

**Comment by gustavohenke** [comment]
You'll have to customise your `isDate` validator a bit, its default is `YYYY/MM/DD` for some reason.
[See here for its docs](https://github.com/validatorjs/validator.js/blob/13.9.0/README.md#validators) (sorry, we can't provide thorough docs for these as we just scrub the typescript types - maybe a link to the implementation would be good, though)
