### ISSUE TITLE
isIp is not a function

### ISSUE THREAD

**Issue by vicvarros** [express-validator/express-validator#594]
Using isIp() validation fails:

```
body('ip', validationMessages.FORMAT_IP).isIp()
```

Throwing the next error:
```
TypeError: body(...).isIp is not a function
api         |     at Object.<anonymous> (/usr/src/app/routes/devices/postDevice/validation.js:11:44)
api         |     at Module._compile (internal/modules/cjs/loader.js:702:30)
api         |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
api         |     at Module.load (internal/modules/cjs/loader.js:612:32)
api         |     at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
api         |     at Function.Module._load (internal/modules/cjs/loader.js:543:3)
api         |     at Module.require (internal/modules/cjs/loader.js:650:17)
api         |     at require (internal/modules/cjs/helpers.js:20:18)
api         |     at Object.<anonymous> (/usr/src/app/routes/devices/postDevice/index.js:1:80)
api         |     at Module._compile (internal/modules/cjs/loader.js:702:30)
api         |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
api         |     at Module.load (internal/modules/cjs/loader.js:612:32)
api         |     at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
api         |     at Function.Module._load (internal/modules/cjs/loader.js:543:3)
api         |     at Module.require (internal/modules/cjs/loader.js:650:17)
api         |     at require (internal/modules/cjs/helpers.js:20:18)
api         |     at Object.<anonymous> (/usr/src/app/routes/devices/index.js:5:18)
api         |     at Module._compile (internal/modules/cjs/loader.js:702:30)
api         |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
api         |     at Module.load (internal/modules/cjs/loader.js:612:32)
api         |     at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
api         |     at Function.Module._load (internal/modules/cjs/loader.js:543:3)
```

**Comment by gustavohenke** [comment]
The right one is `isIP`. Check https://github.com/chriso/validator.js#validators for more details.

**Comment by vicvarros** [comment]
Thanks!
