### ISSUE TITLE
Syntax error unexpected token '{'

### ISSUE THREAD

**Issue by prioxis** [express-validator/express-validator#609]
`const { checkSchema, validationResult } = require('../check');
      ^
SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/dh_pcf79k/hypebot.shop/node_modules/express-validator/index.js:1:80)
    at Module._compile (module.js:460:26)` this is the error I get on my VPS running the latest LTS version of node with the latest version of express-validator and express. I'm not sure what to do in order to fix this

**Comment by gustavohenke** [comment]
Latest Node LTS version is 10. It definitely works with express-validator.
Make sure you are running Node v6+.

If you are, then please provide more evidence, otherwise I may not be able to help you.

**Comment by gustavohenke** [comment]
Closing due to inactivity.
