### ISSUE TITLE
TypeError: expressValidator is not a function

### ISSUE THREAD

**Issue by kirankamatmgm** [express-validator/express-validator#756]
below is code Im using for my mini project but its not working
 const express=require('express');
const app=express();
const mongoose=require('mongoose');
const morgan=require('morgan');
const bodyParser=require('body-parser');
const expressValidator=require('express-validator');
const dotenv=require('dotenv').config();
mongoose.connect(process.env.MONGO_URI)
.then(()=>console.log('DB'))
mongoose.connection.on('error', err =>{
    console.log('DB error: ${err.message}');
});
const postRoutes=require("./routes/post");
app.use(morgan("dev"));
app.use(bodyParser.json());
app.use(expressValidator());
app.use('/',postRoutes);
const port = process.env.PORT || 8080;
app.listen(port, () => {
    console.log(`hi its listening: ${port}!`);
});

and showing below error 
app.use(expressValidator());
        ^

TypeError: expressValidator is not a function
    at Object.<anonymous> (/home/kirankamath/A/Project/node_react/basicNodeServer/app.js:26:9)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

mainly cant expressValidator is not a function
please help me to resolve this

**Comment by gustavohenke** [comment]
Please refrain from using this syntax if you're following a tutorial, it's outdated and has been called "legacy" for over 2 years now.

Also there are quite a few issues on this tracker about this, please refer to #735 which is the most popular at the moment.
