### ISSUE TITLE
isPostalCode fails with "Unknown Locale"

### ISSUE THREAD

**Issue by sethgoodluck** [express-validator/express-validator#773]
Hey all, going through and using the express-validator and was running into an issue where I was trying to validate a US Postal Code. 

Not sure if there is a bug in the package or a bug between my ears.
I was hoping someone could show me the correct way to run express-validator on a postal code. 

If I remove the zipcode check, everything hums as expected. Attempts to use a zipcode check fail outright though. 

**Relevant failing check attempts:**
`check('zipcode', 'Please provide a valid U.S. zipcode').isPostalCode({ locale: 'US' })` 
OR
`check('zipcode', 'Please provide a valid U.S. zipcode').isPostalCode()` 

**stack trace:** 
`Error: Invalid locale 'undefined'
    at StandardValidation._default [as validator] (/Users/sethmartin/Projects/practice/devconnector/node_modules/validator/lib/isPostalCode.js:95:9)
    at StandardValidation.<anonymous> (/Users/sethmartin/Projects/practice/devconnector/node_modules/express-validator/src/context-items/standard-validation.js:20:33)
    at Generator.next (<anonymous>)
    at /Users/sethmartin/Projects/practice/devconnector/node_modules/express-validator/src/context-items/standard-validation.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/sethmartin/Projects/practice/devconnector/node_modules/express-validator/src/context-items/standard-validation.js:3:12)
    at StandardValidation.run (/Users/sethmartin/Projects/practice/devconnector/node_modules/express-validator/src/context-items/standard-validation.js:19:16)
    at ContextRunnerImpl.<anonymous> (/Users/sethmartin/Projects/practice/devconnector/node_modules/express-validator/src/chain/context-runner-impl.js:31:43)
    at Generator.next (<anonymous>)
    at /Users/sethmartin/Projects/practice/devconnector/node_modules/express-validator/src/chain/context-runner-impl.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/sethmartin/Projects/practice/devconnector/node_modules/express-validator/src/chain/context-runner-impl.js:3:12)
    at context.getData.map (/Users/sethmartin/Projects/practice/devconnector/node_modules/express-validator/src/chain/context-runner-impl.js:25:92)
    at Array.map (<anonymous>)
    at ContextRunnerImpl.<anonymous> (/Users/sethmartin/Projects/practice/devconnector/node_modules/express-validator/src/chain/context-runner-impl.js:25:74)
    at Generator.next (<anonymous>)`

**Comment by gustavohenke** [comment]
express-validator only mimics what validator does:
https://github.com/express-validator/express-validator/blob/6e8e5215503adcebc7ba3d0e1b5ff909b5b313b6/declarations/validator.d.ts#L81-L84

So you should use it like this:

```
check('zipcode').isPostalCode('US')
```
