### ISSUE TITLE
Error using express-validator SyntaxError: Unexpected token const { checkSchema, validationResult }

### ISSUE THREAD

**Issue by denisg-g** [express-validator/express-validator#780]
Im using express-validator with normal sintaxis and it works fine but when trying to deploy to production it gets an error like this 

` node app.js

/var/www/html/ApiRao/node_modules/express-validator/lib/express_validator.js:4
const { checkSchema, validationResult } = require('../check');
      ^
SyntaxError: Unexpected token {
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/html/ApiRao/node_modules/express-validator/index.js:1:80)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
`
I have been searching with this error and found that can be version of node 

My node version: v0.10.25
npm version: 1.3.10
os: ubuntu 14.04

**Comment by gustavohenke** [comment]
express-validator v5 requires Node.js 6+.
