### ISSUE TITLE
Error with the demo - Windows10 64bits

### ISSUE THREAD

**Issue by MatteoGauthier** [express-validator/express-validator#798]
```bash
      throw new Error('Most middleware (like ' + name + ') is no longer bundled with Express and must be installed separately. Please see https://github.com/senchalabs/connect#middleware.');
      ^

Error: Most middleware (like json) is no longer bundled with Express and must be installed separately. Please see https://github.com/senchalabs/connect#middleware.
    at Function.get (C:\Users\hdesorme\MattTemp\NodeGoogleCalendarTutorial-master\node_modules\express\lib\express.js:89:13)
    at Object.<anonymous> (C:\Users\hdesorme\MattTemp\NodeGoogleCalendarTutorial-master\test.js:5:17)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11
```

**Comment by gustavohenke** [comment]
Can you provide more information?
Which versions are you running?

**Comment by fedeci** [comment]
I think this was related to `express` that removed the `json` and `bodyParser` middlewares and then added them again.
