### ISSUE TITLE
6.2.0 working , 6.4.0 not working

### ISSUE THREAD

**Issue by jondo89** [express-validator/express-validator#855]
```
/app/node_modules/express-validator/src/middlewares/one-of.js:7
2020-04-02T05:29:51.024759+00:00 app[web.1]:     return async (req, _res, next) => {
2020-04-02T05:29:51.024760+00:00 app[web.1]:                  ^
2020-04-02T05:29:51.024760+00:00 app[web.1]: SyntaxError: Unexpected token (
2020-04-02T05:29:51.024760+00:00 app[web.1]:     at createScript (vm.js:56:10)
2020-04-02T05:29:51.024761+00:00 app[web.1]:     at Object.runInThisContext (vm.js:97:10)
2020-04-02T05:29:51.024761+00:00 app[web.1]:     at Module._compile (module.js:542:28)
2020-04-02T05:29:51.024761+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:579:10)
2020-04-02T05:29:51.024762+00:00 app[web.1]:     at Module.load (module.js:487:32)
2020-04-02T05:29:51.024762+00:00 app[web.1]:     at tryModuleLoad (module.js:446:12)
2020-04-02T05:29:51.024762+00:00 app[web.1]:     at Function.Module._load (module.js:438:3)
2020-04-02T05:29:51.024763+00:00 app[web.1]:     at Module.require (module.js:497:17)
2020-04-02T05:29:51.024763+00:00 app[web.1]:     at require (internal/module.js:20:19)
2020-04-02T05:29:51.024764+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/express-validator/src/index.js:6:10)
2020-04-02T05:55:28.905743+00:00 heroku[web.1]: State changed from crashed to starting
```

**Comment by gustavohenke** [comment]
Which node version are you using?

**Comment by jondo89** [comment]
Ok , thanks for the prompt response , and apoligies for my tardiness , 
Running node --version from Heroku bash shows
v6.14.4

Heroku not working with 6.4.0 , works with 6.2.0 , retested.
Strangly the 6.4.0 works on localhost , but not on the heroku.

**Comment by gustavohenke** [comment]
Can you specify a higher Node.js version for your Heroku instance?
What's your Node.js version locally?

**As an explanation to why v6.2.0 used to work:**
express-validator v6 supports Node.js 8+, and our TypeScript compilation target was set to an older ECMAScript version which would work Node.js 6.
Changing that was a hunch for fixing #824.
