### ISSUE TITLE
TypeError: chain.run is not a function

### ISSUE THREAD

**Issue by xaphod** [express-validator/express-validator#905]
With 6.6.0 when I add this...
```
    oneOf([
      body('name').not().isEmpty(),
      body('passcode').exists(),
      body('sessionsOnlyFlag').not().isEmpty(),
      body('colors').exists(),
      body('imageFilename').not().isEmpty,
    ]),
```

... I get this:

```
>  TypeError: chain.run is not a function
>      at Promise.all.group.map.chain (/functions/api/node_modules/express-validator/src/middlewares/one-of.js:12:73)
>      at Array.map (<anonymous>)
>      at chains.map (/functions/api/node_modules/express-validator/src/middlewares/one-of.js:12:54)
>      at Array.map (<anonymous>)
>      at /functions/api/node_modules/express-validator/src/middlewares/one-of.js:10:33
>      at Layer.handle [as handle_request] (/functions/api/node_modules/express/lib/router/layer.js:95:5)
>      at next (/functions/api/node_modules/express/lib/router/route.js:137:13)
>      at Route.dispatch (/functions/api/node_modules/express/lib/router/route.js:112:3)
>      at Layer.handle [as handle_request] (/functions/api/node_modules/express/lib/router/layer.js:95:5)
>      at /functions/api/node_modules/express/lib/router/index.js:281:22
```

... what am I likely to be doing wrong?

Here is the full context. Removing the `oneOf` fixes the crash:
```
router.patch('/:galleryId',
  [
    oneOf([
      body('name').not().isEmpty(),
      body('passcode').exists(),
      body('sessionsOnlyFlag').not().isEmpty(),
      body('colors').exists(),
      body('imageFilename').not().isEmpty,
    ]),
    body('sessionsOnlyFlag', 'Must be boolean')
      .if(body('sessionsOnlyFlag').exists())
      .isBoolean()
      .toBoolean(),
    body('colors', 'Must be an array')
      .if(body('colors').exists())
      .isArray(),
    body('imageFilename', 'Must be a string')
      .if(body('imageFilename').exists())
      .isString(),
  ],
  async (req, res, next) => {
  ...
```

**Comment by liqiang372** [comment]
```ts
body('imageFilename').not().isEmpty,  <---- parenthesis?
```
it should be `isEmpty()`?

A tip for debugging, use binary removal method, which means when you find removing oneOf works, then try to remove half code inside oneOf until you find the culprit line.

Also it would be great you can create a minimum reproducible repo, and most of time you can find it out by yourself.

**Comment by xaphod** [comment]
Thanks, that was it. And thanks for the tips, appreciated. I haven't had to resort to tactics like that in a long time (i'm coming from static langs like swift...)
